### PR TITLE
Add missing BOOST_PYTHON_DECL decorators to NumPy.

### PR DESCRIPTION
**Pull request by stefanseefeld**

### CODE REVIEW

**Comment by jhunold** [comment]
This should not work. You need a separate set of macros for each separate dll. 
Steps:
- make a copy of `config.hpp`for NumPy
- change the macros
- use them  instead of `BOOST_PYTHON_DECL`

I'll try to fix this on Friday

**Comment by SPKorhonen** [comment]
@jhunold: Please see my pull request #110 on this same issue #98

**Comment by SPKorhonen** [comment]
@stefanseefeld and @jhunold This should probably be closed now as pull request #110 was merged.

**Comment by stefanseefeld** [comment]
Obsoleted by https://github.com/boostorg/python/commit/bd7b8ecba5c211c3361c4a9af82a7a527bed384e

**Pull request closed without merging**
