### PR TITLE
ndarray.shape,strides act more like their python counterparts see #157

### PR DESCRIPTION
**Pull request by mborgerding**
addresses #157
Unit tests added for to verify correct behavior for shape(k),strides(k) with negative indexing.  Verify IndexError raised when k out of bounds.

### CODE REVIEW

**Comment by mborgerding** [comment]
@stefanseefeld , I agree the changes shouldn't be lumped together.  That was not my intent, but github did it on its own (I may've missed something) .  If you feel they should be separated, I can try again, maybe rebasing both changes from the master branch would force github to make them separate PRs.

**Comment by stefanseefeld** [comment]
Yeah, simply move the second one into a separate branch from which you can submit another PR. Sorry it's all a bit formal, but with practice it becomes easier ;-)

**Comment by mborgerding** [comment]
Split this into two PRs. From now on I'll know not to believe that github's "Create New Pull Request" will actually create a _New_ pull request.

**Comment by stefanseefeld** [comment]
FWIW, you could simply have added another commit reverting the previous one (which I could have squash-and-merged as one - so only the first one would have been visible), or you could have force-pushed an update removing the second commit.
But of course, starting over with a new PR works, too. :-)

**Pull request closed without merging**
